name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release cmd/protoc-gen-go-grpc
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'cmd/protoc-gen-go-grpc/')
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [386, amd64]
        exclude:
          - goos: darwin
            goarch: 386

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: 'true'
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Download dependencies
        run: |
          go mod download
          make proto
      - name: Prepare build directory
        run: |
          mkdir -p build/
          cp README.md build/
          cp LICENSE build/
      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          make core
      - name: Create package
        id: package
        run: |
          PACKAGE_NAME=sailgame.core.${GITHUB_REF#refs/tags/}.${{ matrix.goos }}.${{ matrix.goarch }}.tar.gz
          tar -czvf $PACKAGE_NAME -C build .
          echo ::set-output name=name::${PACKAGE_NAME}
      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.package.outputs.name }}
          asset_name: ${{ steps.package.outputs.name }}
          asset_content_type: application/gzip
      - name: Push to GitHub Packages
        if: ${{ matrix.goos == 'linux'}}
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sailgame/core/core
          tag_with_ref: true