name: testing

# Trigger on pushes, PRs (excluding documentation changes), and nightly.
on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 * * * # daily at 00:00

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-20.04
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        submodules: 'true'
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: install dependencies
      run: |
        sudo apt install -y make protobuf-compiler
        go mod download
        make proto
    - name: build
      run: |
        make clean
        make
    - name: test
      run: go test -cpu 1,4 -timeout 7m github.com/SailGame/Core/...